import {
  AlertTriangle,
  Bell,
  CalendarDays,
  Camera,
  Check,
  ChevronLeft,
  ChevronRight,
  CloudSun,
  Download,
  Edit3,
  Flame,
  FolderOpen,
  GalleryVerticalEnd,
  ImagePlus,
  LayoutDashboard,
  ListFilter,
  Mail,
  Map,
  MoreHorizontal,
  Plus,
  Search,
  Settings,
  Ticket,
  Trash2,
  Upload,
  Users,
  UserSquare2,
} from "lucide-react";

export const I = {
  alert: <AlertTriangle size={14} />,
  bell: <Bell size={14} />,
  cal: <CalendarDays size={14} />,
  camera: <Camera size={14} />,
  check: <Check size={14} />,
  collapse: <ChevronLeft size={14} />,
  expand: <ChevronRight size={14} />,
  dashboard: <LayoutDashboard size={14} />,
  download: <Download size={14} />,
  edit: <Edit3 size={14} />,
  filter: <ListFilter size={14} />,
  flame: <Flame size={14} />,
  gallery: <GalleryVerticalEnd size={14} />,
  map: <Map size={14} />,
  mail: <Mail size={14} />,
  more: <MoreHorizontal size={14} />,
  plus: <Plus size={14} />,
  pickimg: <ImagePlus size={14} />,
  search: <Search size={14} />,
  settings: <Settings size={14} />,
  staff: <UserSquare2 size={14} />,
  ticket: <Ticket size={14} />,
  uploads: <Upload size={14} />,
  users: <Users size={14} />,
  weather: <CloudSun size={14} />,
  folder: <FolderOpen size={14} />,
  trash: <Trash2 size={14} />,
};
