#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────────
# Installiert den Architecture-Guard als Git Pre-Commit Hook.
# Einmalig ausführen: bash scripts/install-hooks.sh
# ──────────────────────────────────────────────────────────────────────────────
set -euo pipefail

HOOK_DIR="$(git rev-parse --git-dir)/hooks"
HOOK_FILE="$HOOK_DIR/pre-commit"

mkdir -p "$HOOK_DIR"

cat > "$HOOK_FILE" << 'HOOK'
#!/usr/bin/env bash
# Auto-generated by scripts/install-hooks.sh
# Architecture Guard: Kein neues EJS in Portal/Admin

REPO_ROOT="$(git rev-parse --show-toplevel)"

# Prüfe ob neue .ejs-Dateien gestaged sind (außer customer/)
STAGED_EJS=$(git diff --cached --name-only --diff-filter=A | grep '\.ejs$' | grep -v 'tours/views/customer/' || true)
if [ -n "$STAGED_EJS" ]; then
  echo ""
  echo "❌ COMMIT BLOCKIERT: Neue .ejs-Dateien sind nicht erlaubt!"
  echo "   Seit April 2026 werden alle UI-Seiten über React gerendert."
  echo ""
  echo "   Betroffene Dateien:"
  echo "$STAGED_EJS" | sed 's/^/     /'
  echo ""
  echo "   Erstelle stattdessen eine React-Komponente in app/src/"
  echo ""
  exit 1
fi

# Nur .js-Dateien pruefen (nicht Dokumentation/Regeln)
STAGED_JS=$(git diff --cached --name-only -- '*.js' || true)
if [ -n "$STAGED_JS" ]; then
  STAGED_RENDER=$(git diff --cached -U0 -- '*.js' | grep '^+' | grep -v '^+++' | grep "res\.render(['\"]portal/\|res\.render(['\"]admin/" || true)
  if [ -n "$STAGED_RENDER" ]; then
    echo ""
    echo "COMMIT BLOCKIERT: res.render() fuer Portal/Admin ist nicht erlaubt!"
    echo "   Nutze res.redirect() oder res.json() stattdessen."
    echo ""
    echo "   Betroffene Zeilen:"
    echo "$STAGED_RENDER" | sed 's/^/     /'
    echo ""
    exit 1
  fi
fi

exit 0
HOOK

chmod +x "$HOOK_FILE"
echo "✅ Pre-Commit Hook installiert: $HOOK_FILE"
