#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────────
# Installiert den Architecture-Guard als Git Pre-Commit Hook.
# Einmalig ausführen: bash scripts/install-hooks.sh
# ──────────────────────────────────────────────────────────────────────────────
set -euo pipefail

HOOK_DIR="$(git rev-parse --git-dir)/hooks"
HOOK_FILE="$HOOK_DIR/pre-commit"

mkdir -p "$HOOK_DIR"

cat > "$HOOK_FILE" << 'HOOK'
#!/usr/bin/env bash
# Auto-generated by scripts/install-hooks.sh
# Guards: Architecture (kein EJS) + Documentation (docs/ mitpflegen)

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

# ── Guard 1: Keine neuen .ejs-Dateien (außer customer/) ──────────────────────
STAGED_EJS=$(git diff --cached --name-only --diff-filter=A | grep '\.ejs$' | grep -v 'tours/views/customer/' || true)
if [ -n "$STAGED_EJS" ]; then
  echo ""
  echo "❌ COMMIT BLOCKIERT: Neue .ejs-Dateien sind nicht erlaubt!"
  echo "   Seit April 2026 werden alle UI-Seiten über React gerendert."
  echo ""
  echo "   Betroffene Dateien:"
  echo "$STAGED_EJS" | sed 's/^/     /'
  echo ""
  echo "   Erstelle stattdessen eine React-Komponente in app/src/"
  echo ""
  exit 1
fi

# ── Guard 2: Kein res.render() für Portal/Admin ───────────────────────────────
STAGED_JS=$(git diff --cached --name-only -- '*.js' || true)
if [ -n "$STAGED_JS" ]; then
  STAGED_RENDER=$(git diff --cached -U0 -- '*.js' | grep '^+' | grep -v '^+++' | grep "res\.render(['\"]portal/\|res\.render(['\"]admin/" || true)
  if [ -n "$STAGED_RENDER" ]; then
    echo ""
    echo "COMMIT BLOCKIERT: res.render() fuer Portal/Admin ist nicht erlaubt!"
    echo "   Nutze res.redirect() oder res.json() stattdessen."
    echo ""
    echo "   Betroffene Zeilen:"
    echo "$STAGED_RENDER" | sed 's/^/     /'
    echo ""
    exit 1
  fi
fi

# ── Guard 3: Dokumentations-Hinweis (kein harter Block) ─────────────────────
# Wenn neue Migrationen oder Route-Dateien gestaged sind, erinnern
STAGED_MIGRATIONS=$(git diff --cached --name-only --diff-filter=A \
  | grep -E '(migrations?/.*\.sql|schema.*\.sql)' || true)
STAGED_NEW_ROUTES=$(git diff --cached --name-only --diff-filter=A \
  | grep -E '(tours/routes/|booking/.*routes.*\.js$)' || true)
STAGED_NEW_FLOWS=$(git diff --cached --name-only --diff-filter=A \
  | grep -E 'docs/FLOWS_.*\.md' || true)

NEEDS_DOCS_UPDATE=0

if [ -n "$STAGED_MIGRATIONS" ]; then
  NEEDS_DOCS_UPDATE=1
  echo ""
  echo "📋 HINWEIS: Neue SQL-Migrationen detected — bitte docs/ mitpflegen:"
  echo "$STAGED_MIGRATIONS" | sed 's/^/   /'
  echo "   → docs/SCHEMA_FULL.md aktualisieren"
  echo "   → Passende docs/FLOWS_*.md aktualisieren"
fi

if [ -n "$STAGED_NEW_ROUTES" ]; then
  NEEDS_DOCS_UPDATE=1
  echo ""
  echo "📋 HINWEIS: Neue Route-Dateien detected — bitte docs/ mitpflegen:"
  echo "$STAGED_NEW_ROUTES" | sed 's/^/   /'
  echo "   → Passende docs/FLOWS_*.md aktualisieren"
fi

if [ -n "$STAGED_NEW_FLOWS" ]; then
  # Prüfen ob DATA_FIELDS.md auch gestaged ist
  UPDATED_INDEX=$(git diff --cached --name-only | grep -E '(DATA_FIELDS\.md|data-fields\.mdc)' || true)
  if [ -z "$UPDATED_INDEX" ]; then
    NEEDS_DOCS_UPDATE=1
    echo ""
    echo "📋 HINWEIS: Neue docs/FLOWS_*.md ohne Index-Update:"
    echo "$STAGED_NEW_FLOWS" | sed 's/^/   /'
    echo "   → DATA_FIELDS.md aktualisieren (neue Datei in Tabelle eintragen)"
    echo "   → .cursor/rules/data-fields.mdc erweitern"
  fi
fi

if [ "$NEEDS_DOCS_UPDATE" -gt 0 ]; then
  echo ""
  echo "   (Commit wird NICHT blockiert — aber bitte im nächsten Commit nachholen)"
  echo ""
fi

exit 0
HOOK

chmod +x "$HOOK_FILE"
echo "✅ Pre-Commit Hook installiert: $HOOK_FILE"
